sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: abc123

  alioss:
    endpoint: oss-cn-shenzhen.aliyuncs.com
    access-key-id: ${ALIBABA_ACCESS_KEY_ID}
    access-key-secret: ${ALIBABA_ACCESS_KEY_SECRET}
    bucket-name: weiyi-only

  wechat:
    appid: wx59146ca0023e93d3
    secret: e831b1a197f1af66653f3986739ed01d
spring:
  redis:
    host: localhost
    port: 6379
    database: 0
